### ISSUE TITLE
ldconfig not found

### ISSUE THREAD

**Issue by robot144** [meggart/NetCDF.jl#121] opened 2020-04-07 08:50 UTC
Building this package seems to trigger a call to 'ldconfig -p' since recently, which fails on my opensuse15.1 system as a normal user since ldconfig is in /sbin which is not in the path for a normal user. Adding /sbin to the path is a workaround, but perhaps it is more convenient/safer to fix this in the package?

Keep up the good work for this excellent package,
  Martin

**Comment by visr** [comment] 2020-04-07 09:35
Hi Martin,

I'll close this as a duplicate of #115. Would be great to have this resolved in BinDeps.jl.

**Closed as completed by visr** 2020-04-07 09:35 UTC
