### ISSUE TITLE
Illegal Instruction in Julia 1.0.1 (conda forge)

### ISSUE THREAD

**Issue by meteorologytoday** [meggart/NetCDF.jl#74] opened 2018-10-30 00:11 UTC
I am not sure if NetCDF.jl is supposed to work in 1.0.1 or not. I got error with the same code in the README part with Dict modified to 1.0 syntax. Hope this might help developing.

## Code:
```
using NetCDF

filename   = "myfile.nc"
varname    = "var1"
attribs    = Dict("units"    => "mm/d",
              "data_min" => 0.0,
              "data_max" => 87.0)

nccreate(filename, varname, "x1", 11:20, "t", 20, Dict("units"=>"s"), atts=attribs)

```

## Output:
```
Unreachable reached at 0x7fc9e2b25633

signal (4): Illegal instruction
in expression starting at /home/tienyiah/testjulia/testjulia.jl:9
#NcVar#6 at /home/tienyiah/.julia/packages/NetCDF/ttVCN/src/NetCDF.jl:143
unknown function (ip: 0x7fc9e2b256bb)
jl_fptr_trampoline at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:1831
jl_apply_generic at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:2184
Type at ./none:0
jl_fptr_trampoline at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:1831
jl_apply_generic at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:2184
#nccreate#51 at /home/tienyiah/.julia/packages/NetCDF/ttVCN/src/NetCDF.jl:879
jl_fptr_trampoline at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:1831
jl_apply_generic at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:2184
jl_apply at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/julia.h:1537 [inlined]
jl_f__apply at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/builtins.c:556
#nccreate at ./none:0
jl_fptr_trampoline at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:1831
jl_apply_generic at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:2184
do_call at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/interpreter.c:324
eval_value at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/interpreter.c:430
eval_stmt_value at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/interpreter.c:363 [inlined]
eval_body at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/interpreter.c:678
jl_interpret_toplevel_thunk_callback at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/interpreter.c:795
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fc9fd8d85af)
unknown function (ip: 0x7)
jl_interpret_toplevel_thunk at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/interpreter.c:804
jl_toplevel_eval_flex at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/toplevel.c:813
jl_parse_eval_all at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/ast.c:838
jl_load at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/toplevel.c:847
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1041
include at ./sysimg.jl:29
jl_apply_generic at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:2184
exec_options at ./client.jl:229
_start at ./client.jl:421
jl_apply_generic at /home/conda/feedstock_root/build_artifacts/julia_1539816087668/work/src/gf.c:2184
unknown function (ip: 0x401b61)
unknown function (ip: 0x40146b)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x401504)
Allocations: 5453600 (Pool: 5452671; Big: 929); GC: 11
Illegal instruction (core dumped)
```

## Environment Setup
I am using miniconda3 (conda 4.5.11) on CentOS Linux release 7.5.1804 (Core)
```
conda create -y -n julia_test
. activate julia_test
conda install -y libnetcdf
conda install -y -c conda-forge julia
julia -e 'using Pkg; Pkg.add("NetCDF")'
```

## Versioninfo
```
Julia Version 1.0.1
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**Comment by meggart** [comment] 2018-11-29 14:33
Can you try if the issue is fixed after a package update?

**Comment by meteorologytoday** [comment] 2018-12-18 23:50
Hi, thanks for the reply.
I remove and reinstall NetCDF v0.7.2
Now another problem with overloading functions comes up:
(Here the content of the file netcdf_test.jl is the code I posted at first.)
```
ERROR: LoadError: MethodError: no method matching iscontiguous(::UnitRange{Int64})
Closest candidates are:
  iscontiguous(!Matched::SubArray) at subarray.jl:286
  iscontiguous(!Matched::Type{#s57} where #s57<:(SubArray{T,N,P,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where P where N where T)) at subarray.jl:288
  iscontiguous(!Matched::Type{#s57} where #s57<:SubArray) at subarray.jl:287
Stacktrace:
 [1] #putvar#31(::Array{Int64,1}, ::Array{Int64,1}, ::Function, ::NcVar{Int64,1,10}, ::UnitRange{Int64}) at /home/tienyiah/.julia/packages/NetCDF/61OwG/src/NetCDF.jl:437
 [2] (::getfield(NetCDF, Symbol("#kw##putvar")))(::NamedTuple{(:start, :count),Tuple{Array{Int64,1},Array{Int64,1}}}, ::typeof(NetCDF.putvar), ::NcVar{Int64,1,10}, ::UnitRange{Int64}) at ./none:0
 [3] #putvar#30(::Array{Int64,1}, ::Array{Int64,1}, ::Function, ::NcFile, ::String, ::UnitRange{Int64}) at /home/tienyiah/.julia/packages/NetCDF/61OwG/src/NetCDF.jl:421
 [4] putvar(::NcFile, ::String, ::UnitRange{Int64}) at /home/tienyiah/.julia/packages/NetCDF/61OwG/src/NetCDF.jl:421
 [5] #create#38(::Dict{Any,Any}, ::UInt16, ::Function, ::String, ::Array{NcVar,1}) at /home/tienyiah/.julia/packages/NetCDF/61OwG/src/NetCDF.jl:634
 [6] #create at ./none:0 [inlined]
 [7] #create#39(::Dict{Any,Any}, ::UInt16, ::Function, ::String, ::NcVar{Float64,2,6}) at /home/tienyiah/.julia/packages/NetCDF/61OwG/src/NetCDF.jl:641
 [8] (::getfield(NetCDF, Symbol("#kw##create")))(::NamedTuple{(:gatts, :mode),Tuple{Dict{Any,Any},UInt16}}, ::typeof(NetCDF.create), ::String, ::NcVar{Float64,2,6}) at ./none:0
 [9] #nccreate#51(::Dict{String,Any}, ::Dict{Any,Any}, ::Int64, ::Int64, ::UInt16, ::Tuple{Int64}, ::Function, ::String, ::String, ::String, ::Vararg{Any,N} where N) at /home/tienyiah/.julia/packages/NetCDF/61OwG/src/NetCDF.jl:920
 [10] (::getfield(NetCDF, Symbol("#kw##nccreate")))(::NamedTuple{(:atts,),Tuple{Dict{String,Any}}}, ::typeof(nccreate), ::String, ::String, ::String, ::Vararg{Any,N} where N) at ./none:0
 [11] top-level scope at none:0
 [12] include at ./boot.jl:317 [inlined]
 [13] include_relative(::Module, ::String) at ./loading.jl:1041
 [14] include(::Module, ::String) at ./sysimg.jl:29
 [15] exec_options(::Base.JLOptions) at ./client.jl:229
 [16] _start() at ./client.jl:421
in expression starting at /home/tienyiah/testjulia/netcdf_test.jl:9
```

**Comment by jarlela** [comment] 2018-12-19 08:33
Your current problem is reported as #80

**Comment by meggart** [comment] 2019-08-09 07:45
Closing as this is now a duplicate of #80

**Closed as completed by meggart** 2019-08-09 07:45 UTC
