### ISSUE TITLE
Could not use nccreate in julia pro

### ISSUE THREAD

**Issue by fzhao70** [meggart/NetCDF.jl#77] opened 2018-11-28 14:22 UTC
I use Julia Pro under Windows 10 with version 1.01
Nowadays I find I cannot use the nccreate function in my code.
my code is :

`
filename   = "myfile.nc"
varname    = "var1"
attribs    = Dict("units" => "mm/d", "data_min" => 0.0, "data_max" => 87.0)
nccreate(filename, varname, "x1", 11:20, "t", 20, Dict("units"=>"s"), atts=attribs)
` 

and output is

`
Unreachable reached at 000000001427D6F8

Please submit a bug report with steps to reproduce this fault and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x1427d6f8 -- #NcVar#6 at C:\Users\zfh1997\AppData\Local
\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\NetCDF\ttVCN\src\NetCDF.jl:143
in expression starting at D:\Course\Atmospheric_modeling\hw2\julia_anal.jl:32
#NcVar#6 at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\NetCDF\ttVCN\src\N
etCDF.jl:143
unknown function (ip: 000000001427D778)
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1831
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184 [inlined]
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56
Type at .\none:0
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1831
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
#nccreate#51 at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\NetCDF\ttVCN\s
rc\NetCDF.jl:879
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1831
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:556
#nccreate at .\none:0
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1831
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:430
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:363 [in
lined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:678
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\
interpreter.c:795
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000000E54C2DF)
unknown function (ip: 0000000000000007)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:813
jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src\ast.c:838
include_string at .\loading.jl:1005
#118 at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\Atom\WSz3k\src\eval.jl
:120
withpath at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\CodeTools\hB4Hy\sr
c\utils.jl:30
jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:42
withpath at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\Atom\WSz3k\src\eva
l.jl:46 [inlined]
#117 at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\Atom\WSz3k\src\eval.jl
:117 [inlined]
hideprompt at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\Atom\WSz3k\src\r
epl.jl:76
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
macro expansion at C:\Users\zfh1997\AppData\Local\JuliaPro-1.0.1.1\pkgs-1.0.1.1\packages\Atom\WSz3k\
src\eval.jl:116 [inlined]
#116 at .\task.jl:85
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 60727552 (Pool: 60716750; Big: 10802); GC: 136
`
I run both Julia and Atom with Admin. Thanks a lot.

**Comment by jarlela** [comment] 2018-11-28 14:36
I see a similar error on julia 1.0.2 on debian stretch when running `test NetCDF`

**Comment by meggart** [comment] 2018-11-28 20:42
I can reproduce this on julia 1.0.2 as well. Probably a duplicate of #74 and related to the problems in #76 I will try to look at this as soon as possible.

**Closed as completed** 2018-11-29 11:57 UTC
