### ISSUE TITLE
NcVar MethodError

### ISSUE THREAD

**Issue by zzwei1** [meggart/NetCDF.jl#92] opened 2019-05-21 07:37 UTC
I want to write out some radar variables to a NetCDF file with Julia V1.1.1while it produces the error below,
Running the netcdf example using dictionaries to replace the deprecated curly brackets with Julia V1.0.2 produces the error
Script
# Write out the radar variables
function write_ncfile(filename,lat,lon,lev,times,varnames)
  ###Write to nc-file
  println("Write to nc file ...")

  ncvars = NcVar[]
  xatts = Dict("long_name" => "x (longitude)", "units" => "deg", "missing_value" => -999.0, "_FillValue" => -999.0)
  yatts = Dict("long_name" => "y (latitude)",  "units" => "deg", "missing_value" => -999.0, "_FillValue" => -999.0)
  zatts = Dict("long_name" => "z (eta)",  "units" => "unitless", "missing_value" => -999.0, "_FillValue" => -999.0)
  tatts = Dict("long_name" => "time (minutes)",  "units" => "min", "missing_value" => -999.0, "_FillValue" => -999.0)
  x_dim = NcDim("east_west",collect(1:length(lon[:,1,1])),xatts)
  y_dim = NcDim("south_north",collect(1:length(lat[1,:,1])),yatts)
  z_dim = NcDim("bottom_top",collect(1:length(lev[:,1])),zatts)
  t_dim = NcDim("Time",collect(1:length(times)),tatts)

  for varname in varnames
    atts  = Dict("long_name" => varname, "units" => "???", "missing_value" => -999.0, "_FillValue" => -999.0)
    push!(ncvars,NcVar(varname,[x_dim,y_dim,z_dim,t_dim],atts,Float64))
  end
  atts  = Dict("long_name" => "Latitude", "units" => "deg", "missing_value" => -999.0, "_FillValue" => -999.0)
  push!(ncvars,NcVar("XLAT",[x_dim,y_dim,t_dim],atts,Float64))
  atts  = Dict("long_name" => "Longitude", "units" => "deg", "missing_value" => -999.0, "_FillValue" => -999.0)
  push!(ncvars,NcVar("XLON",[x_dim,y_dim,t_dim],atts,Float64))
  atts  = Dict("long_name" => "Time", "units" => "deg", "missing_value" => -999.0, "_FillValue" => -999.0)
  push!(ncvars,NcVar("XTIME",[t_dim],atts,Float64))
  atts  = Dict("long_name" => "Eta Levels", "units" => "deg", "missing_value" => -999.0, "_FillValue" => -999.0)
  push!(ncvars,NcVar("ZNU",[z_dim,t_dim],atts,Float64))
  nc = NetCDF.create(filename,ncvars)

  NetCDF.putvar(nc,"REFL_10CM",refl)
  NetCDF.putvar(nc,"ZDR",ZDR)
  NetCDF.putvar(nc,"ZV",ZV)
  NetCDF.putvar(nc,"ZH",ZH)
  NetCDF.putvar(nc,"Rayleigh",DBZ)
  NetCDF.putvar(nc,"Zdiff",Zdiff)
  NetCDF.putvar(nc,"QRAIN",qrain)
  NetCDF.putvar(nc,"QNRAIN",qnrain)
  NetCDF.putvar(nc,"XLAT",lat)
  NetCDF.putvar(nc,"XLON",lon)
  NetCDF.putvar(nc,"XTIME",times)
  NetCDF.putvar(nc,"ZNU",lev)

  NetCDF.close(nc)
  return 0
end

Result:
ERROR: LoadError: MethodError: no method matching NcVar(::String, ::Array{NcDim,1}, ::Dict{String,Any}, ::Type{Float64}) Closest candidates are:   NcVar(::AbstractString, ::Union{Array{NcDim,1}, NcDim}; atts, t, compress, chunksize) at /home/.julia/packages/NetCDF/gaxgJ/src/NetCDF.jl:142
Stacktrace:
 [1] write_ncfile(::String, ::Array{Float32,3}, ::Array{Float32,3}, ::Array{Float32,2}, ::Array{Float32,1}, ::Array{String,1}) at /home/julia111/test.jl:294
 [2] top-level scope at none:0
 [3] include at ./boot.jl:326 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:267
 [7] _start() at ./client.jl:436
in expression starting at /home/julia111/test.jl:464

**Comment by visr** [comment] 2019-05-21 11:20
Could you see if you can produce an minimal working example such that we can easily reproduce the issue? See https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757 for more information.

It would also be worthwhile to know if you see the same issue on master (`pkg> add NetCDF#master`) as well.

However, when getting the docstring for `NcVar` with `?NcVar` in the REPL, I see:

```
    NcVar(name::AbstractString,dimin::Union{NcDim,Array{NcDim,1}}

Creates a new NetCDF variable `name` in memory. The variable is associated to a
list of NetCDF dimensions specified by `dimin`.

### Keyword arguments

* `atts` Dictionary representing the variables attributes
* `t` either a Julia type, (one of `Int16`, `Int32`, `Float32`, `Float64`, `String`) or a NetCDF data type (`NC_SHORT`, `NC_INT`, `NC_FLOAT`, `NC_DOUBLE`, `NC_CHAR`, `NC_STRING`) determines the data type of the variable. Defaults to -1
* `compress` Integer which sets the compression level of the variable for NetCDF4 files. Defaults to -1 (no compression). Compression levels of 1..9 are valid
```

So the problem seems to be that you should specify your keyword arguments as such, so instead of

```julia
NcVar(varname,[x_dim,y_dim,z_dim,t_dim],atts,Float64)
```
do
```julia
NcVar(varname, [x_dim, y_dim, z_dim, t_dim]; atts=atts, t=Float64)
```

**Comment by jarlela** [comment] 2019-05-22 09:19
Execution of the example included in `examples/low.jl` in this package will give this error. The example should be fixed to be consistent with the current API.

**Closed as completed** 2019-05-27 13:25 UTC
